### ISSUE TITLE
this os doesnt run win32, uwp or linux apps

### ISSUE THREAD

**Issue by AestheticalZ** [rounk-ctrl/niceos#3]
wtf this os is CRINGE it cant run WIN32 or UWP or LINUX apps 
os SUCKS twitter cancel this pls

**Comment by WIMSATRUN** [comment]
SMH.......................... THIS OPERAION YSTSME IS SO BAD I HOPE NICOE OPERATION SISTEM IS JUST DIED..............................................😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊👏👏👏👏🙌
