### ISSUE TITLE
My NVIDIA GEFORCE RTX 3070 is not working

### ISSUE THREAD

**Issue by MishaTY** [rounk-ctrl/niceos#8]
My NVIDIA GEFORCE RTX 3070 is not beign reconized in this os. Please help. I only see texts on the screeeen. It AlSo SaYs ComMand Not FoUnD. iS my NVIDIA GEFORCE RTX 3070 BroKeN?

**Comment by WIMSATRUN** [comment]
OK i know how to fixing of the prbolem. but jst vuy a new rtx.GOODBYE e

**Comment by AestheticalZ** [comment]
this os needs atleast GEFORCE RTX 3090 dude your gpu is shit

**Comment by MishaTY** [comment]
Just for people wondering, this issue was a joke.
